language: julia
os:
    - linux
julia:
    - 0.6
    - nightly 

notifications:
    email: false
git:
  depth: 999999
addons:
  apt:
    packages:
    - hdf5-tools
  homebrew:
    packages:
    - hdf5
script:
    - julia -e 'Pkg.clone(pwd()); Pkg.test("H5SectionsArrays")'
